# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/kronos
VERILOG_INCLUDE_DIRS += RV-Bench/cores/kronos/rtl/core
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_types.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_hcu.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_alu.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_branch.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_RF.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_IF.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_lsu.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_counter64.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_csr.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_EX.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_agu.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_ID.sv
VERILOG_SOURCES += RV-Bench/cores/kronos/rtl/core/kronos_core.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/kronos.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/kronos
SIM_BUILD = sim_build/kronos
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
