# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SprintRV
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SprintRV/rtl/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SprintRV/rtl/core/include
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/ifu/ifu.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/ifu/if_id.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/ifu/bp.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/dec/id.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/dec/id_ex.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/exu/ex.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/exu/ex_mem.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/exu/div.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/lsu/mem.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/lsu/mem_wb.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/wb/csr.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/wb/gpr.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/ctrl/ctrl.v
VERILOG_SOURCES += RV-Bench/cores/SprintRV/rtl/core/core_top.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/SprintRV.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/SprintRV
SIM_BUILD = sim_build/SprintRV
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
