# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/wb_riscvscale
VERILOG_INCLUDE_DIRS += RV-Bench/cores/wb_riscvscale/.
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_csr_file.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_imm_gen.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_PC_mux.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_mul_div.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_alu.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_src_a_mux.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_src_b_mux.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_regfile.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/vscale_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/wb_riscvscale/wb_vscale.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/wb_riscvscale.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/wb_riscvscale
SIM_BUILD = sim_build/wb_riscvscale
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
