# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -Wno-PROCASSWIRE
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Baby-Risco-5
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Baby-Risco-5/src/core
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/alu_control.v
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/control_unit.v
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/immediate_generator.v
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/alu.v
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/registers.v
VERILOG_SOURCES += RV-Bench/cores/Baby-Risco-5/src/core/core.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Baby-Risco-5.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Baby-Risco-5
SIM_BUILD = sim_build/Baby-Risco-5
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
