# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Pequeno-Risco-5
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Pequeno-Risco-5/src
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/registers.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/immediate_generator.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/alu_control.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/pc.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/instruction_memory.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/mux.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/data_memory.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/control_unit.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/alu.v
VERILOG_SOURCES += RV-Bench/cores/Pequeno-Risco-5/src/core.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Pequeno-Risco-5.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Pequeno-Risco-5
SIM_BUILD = sim_build/Pequeno-Risco-5
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
