# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SuperScalar-RISCV-CPU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/mul.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/predictor.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/alu.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/lsu.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/membuf.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/schedule.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/instrbits.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/instrman.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/sys_csr.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/mprf.v
VERILOG_SOURCES += RV-Bench/cores/SuperScalar-RISCV-CPU/rtl/ssrv_top.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/SuperScalar-RISCV-CPU.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/SuperScalar-RISCV-CPU
SIM_BUILD = sim_build/SuperScalar-RISCV-CPU
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
