# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISC-V-Pipelined-Processor
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/instruction_memory.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/control_unit.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/program_counter.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/EXMEM.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/instruction_parser.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/IDEX.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/adder.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/alu_control.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/2_1mux.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/reg_file.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/MEMWB.sv
VERILOG_SOURCES += RV-Bench/cores/RISC-V-Pipelined-Processor/RISC-V\ Pipelined\ Processor/RISC-V/design.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RISC-V-Pipelined-Processor.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RISC-V-Pipelined-Processor
SIM_BUILD = sim_build/RISC-V-Pipelined-Processor
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
