# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -Wno-TIMESCALEMOD -Wno-IMPLICIT +define+ISA_EXT_F
VERILOG_INCLUDE_DIRS += RV-Bench/cores/airisc_core_complex
VERILOG_INCLUDE_DIRS += RV-Bench/cores/airisc_core_complex/src
VERILOG_INCLUDE_DIRS += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_fpu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_mul_div/src
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_src_a_mux.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_WB_pregs.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_fpu/airi5c_FPU.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_src_b_mux.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_imm_gen.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_decompression.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_prebuf_fifo.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_EX_pregs.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_regfile.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_dmem_latch.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_debug_rom.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_fpu/airi5c_rshifter_static.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_csr_file.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_decode.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_wb_src_mux.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_mul_div/src/airi5c_mul_div.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_debug_module.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_alu.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_PC_mux.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_fetch.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_branch_prediction.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_mem_arbiter.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_fpu/airi5c_rounding_logic.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_dpsram_4x8to32bit_wrapper.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_core.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/airi5c_sync_to_hasti_bridge.v
VERILOG_SOURCES += RV-Bench/cores/airisc_core_complex/src/modules/airi5c_fpu/airi5c_rshifter.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/airisc_core_complex.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/airisc_core_complex
SIM_BUILD = sim_build/airisc_core_complex
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
