# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -DTARGET_IF_AXI
VERILOG_INCLUDE_DIRS += RV-Bench/cores/nox
VERILOG_INCLUDE_DIRS += RV-Bench/cores/nox/rtl/inc
VERILOG_INCLUDE_DIRS += RV-Bench/cores/nox/bus_arch_sv_pkg
VERILOG_INCLUDE_DIRS += RV-Bench/cores/nox/rtl
VERILOG_SOURCES += RV-Bench/cores/nox/bus_arch_sv_pkg/amba_axi_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/inc/nox_utils_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/reset_sync.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/csr.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/fifo_nox.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/register_file.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/fetch.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/cb_to_axi.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/lsu.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/execute.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/decode.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/wb.sv
VERILOG_SOURCES += RV-Bench/cores/nox/rtl/nox.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/nox.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/nox
SIM_BUILD = sim_build/nox
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
