# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2012 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += cores/Grande-Risco-5_complete
VERILOG_INCLUDE_DIRS += cores/Grande-Risco-5_complete/rtl/core
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/grande_risco5_types.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/alu.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/alu_control.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/branch_prediction.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/cache_request_multiplexer.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/csr_unit.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/d_cache.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/EXMEM.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/forwarding_unit.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/Grande_Risco5.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/i_cache.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/IDEX.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/IFID.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/immediate_generator.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/invalid_ir_check.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/ir_decomp.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/mdu.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/MEMWB.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/mux.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/registers.sv
VERILOG_SOURCES += cores/Grande-Risco-5_complete/rtl/core/core.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/Grande-Risco-5_complete.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Grande-Risco-5_complete
SIM_BUILD = sim_build/Grande-Risco-5_complete
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
