# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SparrowRV
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SparrowRV/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/SparrowRV/rtl/core
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/idex.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/dpram.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/iram.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/csr.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/div.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/defines.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/regs.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/sctr.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/trap.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/rstc.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/W25Q128JVxIM.v
VERILOG_SOURCES += RV-Bench/cores/SparrowRV/rtl/core/core.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/SparrowRV.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/SparrowRV
SIM_BUILD = sim_build/SparrowRV
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
