# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/datapath
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/adder
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/instruction_memory
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/register_file
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/Mux2x1
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ALU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/program_counter
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/extend
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit/Main_decoder
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit/ALU_decoder
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/cpu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/data_memory
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/cpu/cpu.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/datapath/datapath.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit/Control_Unit.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/adder/adder.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/instruction_memory/instruction_memory.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/register_file/register_file.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/program_counter/program_counter.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/data_memory/data_memory.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit/ALU_decoder/ALU_decoder.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/extend/extend.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ALU/ALU.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/ENTREGA/Mux2x1/Mux2x1.v
VERILOG_SOURCES += RV-Bench/cores/RISCV_Single_Cycle/Control_Unit/Main_decoder/Main_decoder.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RISCV_Single_Cycle.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RISCV_Single_Cycle
SIM_BUILD = sim_build/RISCV_Single_Cycle
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
