# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore +define+PROCESSORCI_LOW_ADDR_MEMORY
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU/memory/Intel/cyclone10_LP
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU/common/master_platform
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU/common/MachXO3D_breakout
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU/common
VERILOG_INCLUDE_DIRS += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/PulseRain_Reindeer_core.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_CSR.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_controller.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_data_access.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_execution_unit.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_fetch_instruction.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_instruction_decode.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_machine_timer.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_memory.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_mm_reg.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/Reindeer_reg_file.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/mul_div/absolute_value.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/mul_div/long_slow_div_denom_reg.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/submodules/FRV2100/source/mul_div/mul_div_32.sv
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/common/MachXO3D_breakout/config.vh
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/common/master_platform/config.vh
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/common/common.vh
VERILOG_SOURCES += RV-Bench/cores/PulseRain_RISCV_MCU/memory/Intel/cyclone10_LP/dual_port_ram.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/PulseRain_RISCV_MCU.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/PulseRain_RISCV_MCU
SIM_BUILD = sim_build/PulseRain_RISCV_MCU
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
