# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -Wno-TIMESCALEMOD -Wno-WIDTH --timing
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE/rtl/wb
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE/rtl/idex/srt4
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE/rtl/ifu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/ZC-RISCV-CORE/rtl/idex
VERILOG_SOURCES += RV-Bench/cores/ZC-RISCV-CORE/rtl/cpu_top.v
VERILOG_SOURCES += RV-Bench/cores/ZC-RISCV-CORE/rtl/wb/cmt_unit.v
VERILOG_SOURCES += RV-Bench/cores/ZC-RISCV-CORE/rtl/idex/idex_unit.v
VERILOG_SOURCES += RV-Bench/cores/ZC-RISCV-CORE/rtl/ifu/ifu.v
VERILOG_SOURCES += RV-Bench/cores/ZC-RISCV-CORE/rtl/idex/srt4/srt_4_div.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/ZC-RISCV-CORE.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/ZC-RISCV-CORE
SIM_BUILD = sim_build/ZC-RISCV-CORE
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
