# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -Wno-lint -Wno-TIMESCALEMOD --timing
VERILOG_INCLUDE_DIRS += RV-Bench/cores/soric_project
VERILOG_INCLUDE_DIRS += RV-Bench/cores/soric_project/verilog/rtl/mem
VERILOG_INCLUDE_DIRS += RV-Bench/cores/soric_project/verilog/rtl/cores
VERILOG_INCLUDE_DIRS += RV-Bench/cores/soric_project/verilog/rtl/soric
VERILOG_SOURCES += RV-Bench/cores/soric_project/verilog/rtl/soric/soric_core.v
VERILOG_SOURCES += RV-Bench/cores/soric_project/verilog/rtl/mem/sky130_sram_2kbyte_1rw1r_32x512_8.v
VERILOG_SOURCES += RV-Bench/cores/soric_project/verilog/rtl/cores/flexbex_ibex_core.v
VERILOG_SOURCES += RV-Bench/cores/soric_project/verilog/rtl/cores/ibex_top.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/soric_project.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/soric_project
SIM_BUILD = sim_build/soric_project
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
