# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mmRISC-1
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mmRISC-1/verilog/cpu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mmRISC-1/verilog/debug
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mmRISC-1/verilog/mmRISC
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mmRISC-1/verilog/common
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_debug.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_csr_int.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/debug/debug_cdc.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_fpu32.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/mmRISC/bus_m_ahb.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_csr.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/debug/debug_dm.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_fetch.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_csr_dbg.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/debug/debug_dtm_jtag.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/debug/debug_top.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_datapath.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/cpu/cpu_top.v
VERILOG_SOURCES += RV-Bench/cores/mmRISC-1/verilog/mmRISC/mmRISC.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/mmRISC-1.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/mmRISC-1
SIM_BUILD = sim_build/mmRISC-1
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
