# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 +1364-2005ext+.v -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Control
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Global
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Registers
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/ALU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Other\ Units
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Memory
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL/Others
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV32IC-CPU/RTL
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Global/values.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/memAddressSelectUnit.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Control/BranchUnit.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/SignExtend.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/Mux4_1.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/decompression.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/Mux2_1.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Other\ Units/ClkDiv.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/ClkInverter.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Memory/Memory.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/ALU/Full_Adder.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Control/ControlUnit.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/Decoder5_32.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Interrupt_Detector.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Other\ Units/ImmGen.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/RegSrcUnit.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Adder.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Registers/FlipFlop.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/InterruptAddressGenerator.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/CSRRegFile.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/ALU/RippleAdder.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/ALU/ALU.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/PIC.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Other\ Units/ForwardUnit.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Control/ALUControl.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Registers/RegWLoad.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Registers/RegFile.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/RISCV.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/TMRGenerator.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/ShiftLeft1.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/ALU/AdderSub.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/RISCV_TOP.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Others/SSDDriver.v
VERILOG_SOURCES += RV-Bench/cores/RV32IC-CPU/RTL/Registers/regfileModel.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RV32IC-CPU.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RV32IC-CPU
SIM_BUILD = sim_build/RV32IC-CPU
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
