# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/dv-cpu-rv
VERILOG_INCLUDE_DIRS += RV-Bench/cores/dv-cpu-rv/core/rtl
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_alu.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_dpram.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_mem_map.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_hzd_detect.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_instr_mem.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_rf.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_branch_test.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_data_mem.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_imm_gen.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_alu_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_branch_predict.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_forward.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_div.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_core.v
VERILOG_SOURCES += RV-Bench/cores/dv-cpu-rv/core/rtl/rv_mul.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/dv-cpu-rv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/dv-cpu-rv
SIM_BUILD = sim_build/dv-cpu-rv
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
