# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scr1
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scr1/src/core/pipeline
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scr1/src/includes
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scr1/src/core/primitives
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scr1/src/core
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_tdu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_tapc_shift_reg.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_idu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_tapc_synchronizer.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_ipic.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_hdu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_dmi.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_tapc.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/primitives/scr1_reset_cells.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_dm.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/primitives/scr1_cg.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_clk_ctrl.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_ialu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_scu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_lsu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_exu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_mprf.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_csr.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_ifu.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/pipeline/scr1_pipe_top.sv
VERILOG_SOURCES += RV-Bench/cores/scr1/src/core/scr1_core_top.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/scr1.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/scr1
SIM_BUILD = sim_build/scr1
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
