# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += /home/gabcro/Code/Processor_CI/cores/VexRiscv
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/cores/VexRiscv/VexRiscv.v
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/RV-Bench/wrappers_golden/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/RV-Bench/wrappers_golden/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/RV-Bench/wrappers_golden/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/RV-Bench/wrappers_golden/VexRiscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = /home/gabcro/Code/Processor_CI/processor_ci_inspector/cores_utils_revision11_canary/VexRiscv
SIM_BUILD = sim_build/VexRiscv
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
