# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/tinyriscv
VERILOG_INCLUDE_DIRS += RV-Bench/cores/tinyriscv/rtl/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/tinyriscv/rtl/utils
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/csr_reg.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/regs.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/ex.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/clint.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/id.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/ctrl.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/pc_reg.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/utils/gen_dff.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/id_ex.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/div.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/if_id.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/tinyriscv.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/utils/gen_buf.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/core/rib.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/utils/full_handshake_rx.v
VERILOG_SOURCES += RV-Bench/cores/tinyriscv/rtl/utils/full_handshake_tx.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/tinyriscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/tinyriscv
SIM_BUILD = sim_build/tinyriscv
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
