# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISC-V
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISC-V/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISC-V/core/muldiv
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/control_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/MULDIV_in.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/multiplier_32.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/csr_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/load_store_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/ALU.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/MUL_DIV_out.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/forwarding_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/divider_32.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/MULDIV_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/muldiv/MULDIV_top.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/imm_decoder.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/hazard_detection_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/core.v
VERILOG_SOURCES += RV-Bench/cores/RISC-V/core/core_wb.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RISC-V.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RISC-V
SIM_BUILD = sim_build/RISC-V
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
