# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace
EXTRA_ARGS += --no-public-flat-rw --public-depth 1
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e603_hbird
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e603_hbird/design/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e603_hbird/design/tech
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e603_hbird/design/soc
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/tech/e603_hand_mux_bit.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/tech/e603_gnrl_tech_ram.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/tech/e603_gnrl_tech_sync.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/tech/e603_gnrl_tech_clkgate.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/core/e603_core_wrapper.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/syn/techlib/library/std_lvt/verilog/std_lvt.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/core/e603_core_rams.v
VERILOG_SOURCES += RV-Bench/cores/e603_hbird/design/soc/e603_soc_misc.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/e603_hbird.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/e603_hbird
SIM_BUILD = sim_build/e603_hbird
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
