# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RS5
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RS5/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RS5/RingBuffer/rtl
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/RS5_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/RingBuffer/rtl/RingBuffer.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/aes_unit.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/amo.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/CSRBank.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/decode.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/decompresser.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/div.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/execute.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/fetch.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/lrsc.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/mmu.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/mulNbits.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/mul.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/plic.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/regbank.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/retire.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/rtc.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/vectorUnit.sv
VERILOG_SOURCES += RV-Bench/cores/RS5/rtl/RS5.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RS5.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RS5
SIM_BUILD = sim_build/RS5
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
