# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -DPROCESSOR_CI
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/DataMemory.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/Add4.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/PC.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/Mux2.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/WriteBack.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/Controller.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/ALU.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/BranchCondition.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/InstructionMemory.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/ImmediateGenerator.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/RegisterFile.sv
VERILOG_SOURCES += RV-Bench/cores/Fahad-Habib_RISC-V-Single-Cycle-Processor/Processor.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Fahad-Habib_RISC-V-Single-Cycle-Processor.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Fahad-Habib_RISC-V-Single-Cycle-Processor
SIM_BUILD = sim_build/Fahad-Habib_RISC-V-Single-Cycle-Processor
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
