# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cv32e40p
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cv32e40p/rtl/include
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cv32e40p/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cv32e40p/bhv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/include/cv32e40p_apu_core_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/include/cv32e40p_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_if_stage.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_cs_registers.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_register_file_ff.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_load_store_unit.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_id_stage.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_aligner.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_decoder.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_compressed_decoder.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_fifo.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_prefetch_buffer.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_hwloop_regs.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_mult.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_int_controller.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_ex_stage.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_alu_div.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_alu.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_ff_one.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_popcnt.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_apu_disp.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_controller.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_obi_interface.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_prefetch_controller.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_sleep_unit.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/rtl/cv32e40p_core.sv
VERILOG_SOURCES += RV-Bench/cores/cv32e40p/bhv/cv32e40p_sim_clock_gate.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/cv32e40p.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/cv32e40p
SIM_BUILD = sim_build/cv32e40p
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
