# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore --timing
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e200_opensource
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e200_opensource/rtl/e203/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/e200_opensource/rtl/e203/general
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_csr.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_ifu_ift2icb.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_excp.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_ifu_litebpu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_wbck.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_decode.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_lsuagu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_dpath.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_disp.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_muldiv.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_irq_sync.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_extend_csr.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_branchslv.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_commit.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_rglr.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_csrctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu_bjp.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_alu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_gnrl_dffs.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_gnrl_bufs.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_gnrl_icbs.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_biu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_lsu_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_oitf.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_ifu_minidec.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_ifu_ifetch.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_ifu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_longpwbck.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_clkgate.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_clk_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_1cyc_sram_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu_regfile.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_exu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_sram_icb_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_itcm_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_dtcm_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_reset_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_sim_ram.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/general/sirv_gnrl_ram.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_dtcm_ram.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_itcm_ram.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_srams.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_lsu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_core.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_cpu.v
VERILOG_SOURCES += RV-Bench/cores/e200_opensource/rtl/e203/core/e203_cpu_top.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/e200_opensource.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/e200_opensource
SIM_BUILD = sim_build/e200_opensource
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
