# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 +1364-2005ext+.v -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore +define+UART_FILE=uart.txt
VERILOG_INCLUDE_DIRS += RV-Bench/cores/arRISCado
VERILOG_INCLUDE_DIRS += RV-Bench/cores/arRISCado/project/peripheral
VERILOG_INCLUDE_DIRS += RV-Bench/cores/arRISCado/project
VERILOG_INCLUDE_DIRS += RV-Bench/cores/arRISCado/project/cpu
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/peripheral/buttons.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/register_bank.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/uart.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/decode.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/writeback.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/ram.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/fetch.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/divider.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/alu.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/execute.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu/memory.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/peripheral/pwm_port.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/peripheral/peripheral_manager.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/mmu.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/cpu.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/top.v
VERILOG_SOURCES += RV-Bench/cores/arRISCado/project/rom.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/arRISCado.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/arRISCado
SIM_BUILD = sim_build/arRISCado
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
