// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(sys_clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_OUT8(core_cyc,0,0);
        VL_OUT8(core_stb,0,0);
        VL_OUT8(core_we,0,0);
        VL_OUT8(core_sel,3,0);
        VL_IN8(imem_prog_we,0,0);
        VL_IN8(dmem_prog_we,0,0);
        VL_IN8(core_ack,0,0);
        VL_OUT8(data_mem_cyc,0,0);
        VL_OUT8(data_mem_stb,0,0);
        VL_OUT8(data_mem_we,0,0);
        VL_OUT8(data_mem_sel,3,0);
        VL_IN8(data_mem_ack,0,0);
        CData/*0:0*/ processorci_top__DOT__sys_clk;
        CData/*0:0*/ processorci_top__DOT__rst_n;
        CData/*0:0*/ processorci_top__DOT__core_cyc;
        CData/*0:0*/ processorci_top__DOT__core_stb;
        CData/*0:0*/ processorci_top__DOT__core_we;
        CData/*3:0*/ processorci_top__DOT__core_sel;
        CData/*0:0*/ processorci_top__DOT__imem_prog_we;
        CData/*0:0*/ processorci_top__DOT__dmem_prog_we;
        CData/*0:0*/ processorci_top__DOT__core_ack;
        CData/*0:0*/ processorci_top__DOT__data_mem_cyc;
        CData/*0:0*/ processorci_top__DOT__data_mem_stb;
        CData/*0:0*/ processorci_top__DOT__data_mem_we;
        CData/*3:0*/ processorci_top__DOT__data_mem_sel;
        CData/*0:0*/ processorci_top__DOT__data_mem_ack;
        CData/*0:0*/ processorci_top__DOT__clk_core;
        CData/*0:0*/ processorci_top__DOT__rst_core;
        CData/*0:0*/ processorci_top__DOT___core_ack;
        CData/*0:0*/ processorci_top__DOT___data_mem_ack;
        CData/*0:0*/ processorci_top__DOT__adam_mem_en;
        CData/*0:0*/ processorci_top__DOT__adam_mem_we;
        CData/*3:0*/ processorci_top__DOT__adam_mem_wstrb;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__sys_clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__sys_rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__br_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__stall;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__flush;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__w_regs_en;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__w_regs_addr;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__id_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_func7_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__id_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__id_alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__id_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__id_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__id_mem_write_forward;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__id_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__id_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__ex_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__ex_rs2;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__ex_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_func7_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__ex_rd;
    };
    struct {
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__ex_alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__ex_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__ex_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__ex_regs_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__forwardA;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__forwardB;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__me_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__me_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__me_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__me_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__me_mem_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__me_regs_write;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__me_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__forward_data;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__wb_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__wb_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__pc_stall;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__if_flush;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__br_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__cs;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__we;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__br_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__pc_stall;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT____Vstrobe0;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__w_regs_en;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__w_regs_addr;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__ctrl_stall;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_func7_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_mem_write_forward;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_rs2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__br_addr_mode;
    };
    struct {
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__ctrl_valve;
        CData/*6:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__inst_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_ctrl__DOT__regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__rstn;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__r_regs_addr1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__r_regs_addr2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__w_regs_addr;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__w_regs_en;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__wb_hazard_a;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__wb_hazard_b;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_mem_write;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__forward_data;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__w_en_mem;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__addr_in_word;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__en_mem;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT____Vstrobe0;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__clk;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__w_en_mem;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__en_mem;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__cs;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__we;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_func7_code;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_alu_op;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_br;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__forwardA;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__forwardB;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__br_ctrl;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__alu_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__br_mark;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu__DOT__alu_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu__DOT__br_mark;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu_control__DOT__alu_op;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu_control__DOT__func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu_control__DOT__func7_code;
        CData/*3:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu_control__DOT__alu_ctrl_r;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__ex_mem_read;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__id_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__id_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__ex_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__br_ctrl;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__id_mem_write_forward;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__stall;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__flush;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_hazard_detection__DOT__load_stall;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__ex_rs1;
    };
    struct {
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__ex_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__me_rd;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__wb_rd;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__me_rs2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__me_mem_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__wb_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__me_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__wb_regs_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__forwardA;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__forwardB;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__forward_data;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__ex_hazard_a;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__ex_hazard_b;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__mem_hazard_a;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__mem_hazard_b;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_forwarding__DOT__hazard_data_mem;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__wb_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__wb_func3_code;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__addr_in_word_wb;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT____Vstrobe0;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT____Vstrobe1;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__rstn;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_regs_write;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_func3_code;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_func3_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__rstn;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_mem_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_regs_write;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_func3_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_rs2;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_mem2reg;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_mem_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_regs_write;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__rstn;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_func7_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_ex_flush;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_rs2;
    };
    struct {
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_rs1;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_rs2;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_func3_code;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_func7_code;
        CData/*4:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_rd;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_br;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_mem_read;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_mem2reg;
        CData/*2:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_alu_op;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_mem_write;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_alu_src1;
        CData/*1:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_alu_src2;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_br_addr_mode;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_regs_write;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__clk;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__if_id_flush;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__if_id_stall;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__inst_swift;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__clock;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__syn_rstn;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__rst_nr1;
        CData/*0:0*/ processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__rst_nr2;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_7;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_8;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v0;
        CData/*7:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v1;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v1;
        CData/*7:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v2;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v2;
        CData/*7:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v3;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v3;
        CData/*7:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v4;
        CData/*0:0*/ __VdlySet__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v4;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__clk_core__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__rstn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__processorci_top__DOT__Processor__DOT__u_syn_rst__DOT__rstn__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*11:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__inst_addr_2;
        SData/*11:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__addr;
        SData/*11:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__addr_mem_2;
    };
    struct {
        SData/*11:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__addr;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__mem__v0;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v0;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v1;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v2;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v3;
        SData/*11:0*/ __VdlyDim0__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v4;
        VL_OUT(core_addr,31,0);
        VL_OUT(core_data_out,31,0);
        VL_IN(core_data_in,31,0);
        VL_IN(imem_prog_addr,31,0);
        VL_IN(imem_prog_data,31,0);
        VL_IN(dmem_prog_addr,31,0);
        VL_IN(dmem_prog_data,31,0);
        VL_OUT(imem_fetch_addr,31,0);
        VL_OUT(data_mem_addr,31,0);
        VL_OUT(data_mem_data_out,31,0);
        VL_IN(data_mem_data_in,31,0);
        IData/*31:0*/ processorci_top__DOT__core_addr;
        IData/*31:0*/ processorci_top__DOT__core_data_out;
        IData/*31:0*/ processorci_top__DOT__core_data_in;
        IData/*31:0*/ processorci_top__DOT__imem_prog_addr;
        IData/*31:0*/ processorci_top__DOT__imem_prog_data;
        IData/*31:0*/ processorci_top__DOT__dmem_prog_addr;
        IData/*31:0*/ processorci_top__DOT__dmem_prog_data;
        IData/*31:0*/ processorci_top__DOT__imem_fetch_addr;
        IData/*31:0*/ processorci_top__DOT__data_mem_addr;
        IData/*31:0*/ processorci_top__DOT__data_mem_data_out;
        IData/*31:0*/ processorci_top__DOT__data_mem_data_in;
        IData/*31:0*/ processorci_top__DOT___core_data_in;
        IData/*31:0*/ processorci_top__DOT___data_mem_data_in;
        IData/*31:0*/ processorci_top__DOT__adam_mem_addr;
        IData/*31:0*/ processorci_top__DOT__adam_mem_wdata;
        IData/*31:0*/ processorci_top__DOT__adam_bus_addr;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__br_addr;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__if_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__if_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__id_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__id_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__id_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__id_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__id_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_regs_data2_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__ex_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__me_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__me_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__me_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__wb_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__wb_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__br_addr;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__if_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__if_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__inst_addr;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__inst_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__wdata;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__rdata;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__br_addr;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__pc_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_pc__DOT__pc_next;
    };
    struct {
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__id_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_imm_gen__DOT__inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_imm_gen__DOT__imm_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__r_regs_o1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__r_regs_o2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__me_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__w_data_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__w_data_mem_pre;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__r_data_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__addr_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__addr_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__w_data_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__r_data_mem;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__wdata;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__rdata;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__me_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__ex_regs_data2_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__br_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__op_A;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__op_A_pre;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__op_B;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__op_B_pre;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__br_addr_op_A;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu__DOT__op_A;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu__DOT__op_B;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_ex__DOT__u_alu__DOT__alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__wb_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__wb_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__w_regs_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_wb__DOT__wb_mem_data_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__me_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_mem_data;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_mem_wb__DOT__wb_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__ex_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_ex_mem__DOT__me_alu_o;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__id_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_regs_data1;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_regs_data2;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_id_ex__DOT__ex_imm;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__if_pc;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__if_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__id_inst;
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__id_pc;
    };
    struct {
        IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_reg_if_id__DOT__id_inst_reg;
        IData/*31:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__mem__v0;
        IData/*31:0*/ __VdlyVal__processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem__v0;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 4096> processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> processorci_top__DOT__Processor__DOT__u_stage_id__DOT__u_regs__DOT__reg_bank;
        VlUnpacked<IData/*31:0*/, 4096> processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    std::string processorci_top__DOT__memory_hex_file;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__IROM_SPACE = 0x00001000U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__DATA_WHITH = 0x00000020U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__DATA_SIZE = 8U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__ADDR_WHITH = 0x0000000cU;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__RAM_DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_if__DOT__u_inst_memory__DOT__u_ram_data__DOT__DATA_BYTE = 4U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__RAM_SPACE = 0x00001000U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__ADDR_WIDTH = 0x0000000cU;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__DATA_WHITH = 0x00000020U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__DATA_SIZE = 8U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__ADDR_WHITH = 0x0000000cU;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__RAM_DEPTH = 0x00001000U;
    static constexpr IData/*31:0*/ processorci_top__DOT__Processor__DOT__u_stage_mem__DOT__u_data_memory__DOT__u_ram_data__DOT__DATA_BYTE = 4U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
