# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore -Wno-BLKANDNBLK
VERILOG_INCLUDE_DIRS += RV-Bench/cores/championnan_RISCV
VERILOG_INCLUDE_DIRS += RV-Bench/cores/championnan_RISCV/Lab3/Lab3_SrcCode/CacheSrcCode
VERILOG_INCLUDE_DIRS += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab3/Lab3_SrcCode/CacheSrcCode/cache.sv
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab3/Lab3_SrcCode/CacheSrcCode/main_mem.sv
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab3/Lab3_SrcCode/CacheSrcCode/mem.sv
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ALU.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/BranchDecision.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/CSRRegister.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/Cache/DataCache.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/Cache/InstructionCache.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ControllerDecoder.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/DataExtend.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/AddrMem.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/CtrlMem.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/Reg2Mem.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/Result.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/csrAex.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/csrDex.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ExMemSegReg/csrex.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/GeneralRegister.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/Hazard.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/AddrEx.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/BrTarget.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/CtrlEx.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/Op1.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/Op2.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/PcEx.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/Reg2Ex.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/csrAid.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IdExSegReg/csrDid.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IfIdSegReg/PcId.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/IfIdSegReg/IR.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/ImmExtend.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/MemWbSegReg/AddrWb.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/MemWbSegReg/CtrlWb.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/MemWbSegReg/WbData.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/MemWbSegReg/csrAddrwb.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/MemWbSegReg/csrDwb.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/NPCGenerator.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/PC.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/Parameters.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/RV32ICore.v
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/bht.sv
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/btb.sv
VERILOG_SOURCES += RV-Bench/cores/championnan_RISCV/Lab4/Lab4_SrcCode/lab4-2-Srccode/csrALU.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/championnan_RISCV.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/championnan_RISCV
SIM_BUILD = sim_build/championnan_RISCV
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
