# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV12
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV12/rtl/verilog/pkg
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV12/rtl/verilog/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV12/rtl/verilog/core/ex
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RV12/submodules/memory/rtl/verilog
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/pkg/riscv_rv12_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/pkg/riscv_state_20240411_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/pkg/riscv_opcodes_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/pkg/biu_constants_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/pkg/riscv_du_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_wb.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/ex/riscv_lsu.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/ex/riscv_alu.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_id.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_state_20240411.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1r1w_easic_n3xs.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_rf.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_rsb.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1r1w_generic.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1rw_easic_n3x.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_mem.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_du.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1r1w_lattice.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/ex/riscv_bu.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_dwb.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1rw_generic.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_parcel_queue.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_if.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_pd.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1r1w_easic_n3x.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1r1w.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_bp.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/ex/riscv_mul.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/ex/riscv_div.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_ex.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_queue.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/submodules/memory/rtl/verilog/rl_ram_1rw.sv
VERILOG_SOURCES += RV-Bench/cores/RV12/rtl/verilog/core/riscv_core.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RV12.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RV12
SIM_BUILD = sim_build/RV12
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
