# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore --timing
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Fede997_RISCV-PROCESSOR
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-immgenerator.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-cpu_factorial.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-cpu_test.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-aludec.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-maindec.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-alu.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-datamemory.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-instructionmemory.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-registerfile.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-mux.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-datapath.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-core.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-ffresettable.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-adder.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-cpu_summation.v
VERILOG_SOURCES += RV-Bench/cores/Fede997_RISCV-PROCESSOR/cpuRISCV-controller.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Fede997_RISCV-PROCESSOR.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Fede997_RISCV-PROCESSOR
SIM_BUILD = sim_build/Fede997_RISCV-PROCESSOR
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
