# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/vanilla-riscv
VERILOG_INCLUDE_DIRS += RV-Bench/cores/vanilla-riscv/rtl/core
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_register.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_interrupts.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_core_fetch_buffer.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_csrs.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_decode.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_counters.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_lsu.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_memory.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_alu.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_gprs.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_fetch.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_writeback.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_alu_muldiv.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline_execute.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/vanilla-riscv/rtl/core/frv_core.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/vanilla-riscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/vanilla-riscv
SIM_BUILD = sim_build/vanilla-riscv
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
