# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/IRQ
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/DECO_INSTR
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/FSM
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/MEMORY_INTERFACE
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/REG_FILE
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/ALU
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/UTILITIES
VERILOG_INCLUDE_DIRS += RV-Bench/cores/mriscv/mriscvcore/MULT
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/DECO_INSTR/DECO_INSTR.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/FSM/FSM.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/MEMORY_INTERFACE/MEMORY_INTERFACE.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/ALU/ALU.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/UTILITIES/UTILITY.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/mriscvcore.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/IRQ/IRQ.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/MULT/MULT.v
VERILOG_SOURCES += RV-Bench/cores/mriscv/mriscvcore/REG_FILE/REG_FILE.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/mriscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/mriscv
SIM_BUILD = sim_build/mriscv
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
