# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += cores/mr1
VERILOG_SOURCES += cores/mr1/MR1.v
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += RV-Bench/wrappers_golden/mr1.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/mr1
SIM_BUILD = sim_build/mr1
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
