# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = False
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Hazard3
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Hazard3/hdl/arith
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Hazard3/hdl
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_frontend.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_mul_fast.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_pmp.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_muldiv_seq.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_onehot_priority.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_onehot_encode.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_power_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_triggers.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_instr_decompress.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_decode.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_onehot_priority_dynamic.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_irq_ctrl.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_csr.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_regfile_1w2r.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_priority_encode.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_branchcmp.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_shift_barrel.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/arith/hazard3_alu.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_core.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_cpu_1port.v
VERILOG_SOURCES += RV-Bench/cores/Hazard3/hdl/hazard3_cpu_2port.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Hazard3.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Hazard3
SIM_BUILD = sim_build/Hazard3
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
