# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/rtl/core
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_aessub
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/b_bop
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/p_shfrot
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_aesmix
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/b_lut
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/p_addsub
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_sha3
VERILOG_INCLUDE_DIRS += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_sha256
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_mul.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_lsu.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_csrs.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_long.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_divrem.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_writeback.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_rngif.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/p_addsub/p_addsub.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_aesmix/xc_aesmix.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_pmul.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_leak.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/b_lut/b_lut.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_sha3/xc_sha3.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_interrupts.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu_muldivrem.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_malu/xc_malu.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub_sbox.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_aessub/xc_aessub.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_counters.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_core_fetch_buffer.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_fetch.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/xc_sha256/xc_sha256.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_asi.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/b_bop/b_bop.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_bitwise.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_register.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_memory.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/external/xcrypto/rtl/p_shfrot/p_shfrot.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_alu.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_execute.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline_decode.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_gprs.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/scarv-cpu/rtl/core/frv_core.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/scarv-cpu.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/scarv-cpu
SIM_BUILD = sim_build/scarv-cpu
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
