# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2017 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/Stardusten_riscv
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/ex_mem.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/br_pred.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/id_ex.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/if_id.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/id.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/mem_wb.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/stall_ctl.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/regfile.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/ex.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/mem.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/pc.v
VERILOG_SOURCES += RV-Bench/cores/Stardusten_riscv/riscv.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/Stardusten_riscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/Stardusten_riscv
SIM_BUILD = sim_build/Stardusten_riscv
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
