# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cve2
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cve2/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cve2/vendor/lowrisc_ip/ip/prim/rtl
VERILOG_INCLUDE_DIRS += RV-Bench/cores/cve2/vendor/lowrisc_ip/dv/sv/dv_utils
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_alu.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_compressed_decoder.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_controller.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_counter.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_cs_registers.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_decoder.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_ex_block.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_id_stage.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_if_stage.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_load_store_unit.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_multdiv_slow.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_multdiv_fast.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_prefetch_buffer.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_fetch_fifo.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_register_file_ff.sv
VERILOG_SOURCES += RV-Bench/cores/cve2/rtl/cve2_core.sv
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/cve2.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/cve2
SIM_BUILD = sim_build/cve2
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
