# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2012 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_SOURCES += /home/gabcro/Code/Processor_CI/build/f32c.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/f32c.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/f32c
SIM_BUILD = sim_build/f32c
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
