# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
export OLLAMA = False
COMPILE_ARGS ?= --language 1800-2023 -DSIMULATION -Wno-fatal -Wno-lint --public-flat-rw --trace --trace-structs --trace-underscore
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/mem_stage
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/decode_stage
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/m_unit_extension
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/peripherals
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite_interconnect
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/pipeline_registers
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/fetch_stage
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/execute_stage
VERILOG_INCLUDE_DIRS += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/writeback_stage
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite_interconnect/axi4_lite_addr_map_pkg.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/mem_stage/mem_stage.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/pipeline_registers/mem_wb_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/peripherals/led.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/pipeline_registers/if_id_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_read_master.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/m_unit_extension/m_registers.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/lru_reg.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_write_master.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/pipeline_registers/id_ex_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/peripherals/data_memory.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/btb_read.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/execute_stage/alu.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/hazard_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/m_unit_extension/m_alu.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_write_slave.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/execute_stage/pc_jump.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_master.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/m_unit_extension/m_controller.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/m_unit_extension/riscv_m_unit.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/fetch_stage/instruction_mem.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/writeback_stage/writeback_stage.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/forwarding_unit.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/pipeline_registers/ex_mem_pipeline.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/btb_file.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/fetch_stage/pc.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite_interconnect/axi4_lite_addr_decoder.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/execute_stage/alu_control.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/execute_stage/execute_stage.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/dynamic_branch_predictor.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/btb_write.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/decode_stage/decode_controller.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/fetch_stage/pc_update.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/fetch_stage/fetch_stage.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_read_slave.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite/axi4_lite_slave.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/decode_stage/register_file.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/decode_stage/decode_stage.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/lru_next.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/branch_target_buffer/btb.v
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite_interconnect/axi4_lite_interconnect.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/axi4_lite_peripheral_top.sv
VERILOG_SOURCES += RV-Bench/cores/RISCV-RV32IM-AXI4-Lite-SoC/src/riscv_soc_top.v
VERILOG_SOURCES += wrappers/internal/ahblite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4lite_to_wishbone.sv
VERILOG_SOURCES += wrappers/internal/axi4_to_wishbone.sv
VERILOG_SOURCES += wrappers/RISCV-RV32IM-AXI4-Lite-SoC.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
OUTPUT_DIR = cores_utils/RISCV-RV32IM-AXI4-Lite-SoC
SIM_BUILD = sim_build/RISCV-RV32IM-AXI4-Lite-SoC
PROCESSOR_CI_VERILATOR_ROOT = $(shell verilator -V | sed -n 's/^[[:space:]]*VERILATOR_ROOT[[:space:]]*=[[:space:]]*//p' | head -1)
PROCESSOR_CI_COCOTB_VERILATOR_DIR = $(shell cocotb-config --share)/lib/verilator
BUILD_ARGS += VPATH=$(PROCESSOR_CI_COCOTB_VERILATOR_DIR):$(PROCESSOR_CI_VERILATOR_ROOT)/include:$(PROCESSOR_CI_VERILATOR_ROOT)/include/vltstd
export OUTPUT_DIR
include $(shell cocotb-config --makefiles)/Makefile.sim
